#[derive(Debug)]
pub enum Tags {
    // Image Data Structure
    ImageWidth,
    ImageLength,
    BitsPerSample,
    Compression,
    PhotometricInterpretation,
    Orientation,
    SamplesPerPixel,
    PlanarConfiguration,
    YCbCrSubSampling,
    YCbCrPositioning,
    XResolution,
    YResolution,
    ResolutionUnit,

    // Offset Recording
    StripOffsets,
    RowsPerStrip,
    StripByteCounts,
    JPEGInterchangeFormat,
    JPEGInterchangeFormatLength,

    // Image Data Characteristics
    TransferFunction,
    WhitePoint,
    PrimaryChromaticities,
    YCbCrCoefficients,
    ReferenceBlackWhite,

    // Other
    DateTime,
    ImageDescription,
    Make,
    Model,
    Software,
    Artist,
    Copyright,
}

pub fn get_usize_for_tag(tag: Tags) -> usize {
    match tag {
        Tags::ImageWidth => 256,
        Tags::ImageLength => 257,
        Tags::BitsPerSample => 258,
        Tags::Compression => 259,
        Tags::PhotometricInterpretation => 262,
        Tags::Orientation => 274,
        Tags::SamplesPerPixel => 277,
        Tags::PlanarConfiguration => 284,
        Tags::YCbCrSubSampling => 530,
        Tags::YCbCrPositioning => 531,
        Tags::XResolution => 282,
        Tags::YResolution => 283,
        Tags::ResolutionUnit => 296,
        Tags::StripOffsets => 273,
        Tags::RowsPerStrip => 278,
        Tags::StripByteCounts => 279,
        Tags::JPEGInterchangeFormat => 513,
        Tags::JPEGInterchangeFormatLength => 514,
        Tags::TransferFunction => 301,
        Tags::WhitePoint => 318,
        Tags::PrimaryChromaticities => 319,
        Tags::YCbCrCoefficients => 529,
        Tags::ReferenceBlackWhite => 532,
        Tags::DateTime => 306,
        Tags::ImageDescription => 270,
        Tags::Make => 271,
        Tags::Model => 272,
        Tags::Software => 305,
        Tags::Artist => 315,
        Tags::Copyright => 33432,
    }
}

pub fn get_tag_for_usize(tag: usize) -> Option<Tags> {
    match tag {
        256 => Some(Tags::ImageWidth),
        257 => Some(Tags::ImageLength),
        258 => Some(Tags::BitsPerSample),
        259 => Some(Tags::Compression),
        262 => Some(Tags::PhotometricInterpretation),
        274 => Some(Tags::Orientation),
        277 => Some(Tags::SamplesPerPixel),
        284 => Some(Tags::PlanarConfiguration),
        530 => Some(Tags::YCbCrSubSampling),
        531 => Some(Tags::YCbCrPositioning),
        282 => Some(Tags::XResolution),
        283 => Some(Tags::YResolution),
        296 => Some(Tags::ResolutionUnit),
        273 => Some(Tags::StripOffsets),
        278 => Some(Tags::RowsPerStrip),
        279 => Some(Tags::StripByteCounts),
        513 => Some(Tags::JPEGInterchangeFormat),
        514 => Some(Tags::JPEGInterchangeFormatLength),
        301 => Some(Tags::TransferFunction),
        318 => Some(Tags::WhitePoint),
        319 => Some(Tags::PrimaryChromaticities),
        529 => Some(Tags::YCbCrCoefficients),
        532 => Some(Tags::ReferenceBlackWhite),
        306 => Some(Tags::DateTime),
        270 => Some(Tags::ImageDescription),
        271 => Some(Tags::Make),
        272 => Some(Tags::Model),
        305 => Some(Tags::Software),
        315 => Some(Tags::Artist),
        33432 => Some(Tags::Copyright),
        _ => None,
    }
}
