#[derive(Debug)]
pub enum Tags {
    // Special IFDs
    ExifOffset,
    GPSOffset,
    Interoperability,

    // TIFF
    // Image Data Structure
    ImageWidth,
    ImageLength,
    BitsPerSample,
    Compression,
    PhotometricInterpretation,
    Orientation,
    SamplesPerPixel,
    PlanarConfiguration,
    YCbCrSubSampling,
    YCbCrPositioning,
    XResolution,
    YResolution,
    ResolutionUnit,

    // Offset Recording
    StripOffsets,
    RowsPerStrip,
    StripByteCounts,
    JPEGInterchangeFormat,
    JPEGInterchangeFormatLength,

    // Image Data Characteristics
    TransferFunction,
    WhitePoint,
    PrimaryChromaticities,
    YCbCrCoefficients,
    ReferenceBlackWhite,

    // Other
    DateTime,
    ImageDescription,
    Make,
    Model,
    Software,
    Artist,
    Copyright,

    // Exif
    // Tags Relating to Version
    ExifVersion,
    FlashpixVersion,

    // Tags Relating to ColorSpace
    ColorSpace,
    Gamma,

    // Tags Relating to Image Configuration
    ComponentsConfiguration,
    CompressedBitsPerPixel,
    PixelXDimension,
    PixelYDimension,

    // Tags Relating to User Information
    MakerNote,
    UserComment,

    // Tag Relating to Related File Information
    RelatedSoundFile,

    // Tags Relating to Date and Time
    DateTimeOriginal,
    DateTimeDigitized,
    OffsetTime,
    OffsetTimeOriginal,
    OffsetTimeDigitized,
    SubSecTime,
    SubSecTimeOriginal,
    SubSecTimeDigitized,

    // Tags Relating to Picture-Taking Conditions
    ExposureTime,
    FNumber,
    ExposureProgram,
    SpectralSensitivity,
    PhotographicSensitivity,
    OECF,
    SensitivityType,
    StandardOutputSensitivity,
    RecommendedExposureIndex,
    ISOSpeed,
    ISOSpeedLatitudeyyy,
    ISOSpeedLatitudezzz,
    ShutterSpeedValue,
    ApertureValue,
    BrightnessValue,
    ExposureBiasValue,
    MaxApertureValue,
    SubjectDistance,
    MeteringMode,
    LightSource,
    Flash,
    FocalLength,
    SubjectArea,
    FlashEnergy,
    SpatialFrequencyResponse,
    FocalPlaneXResolution,
    FocalPlaneYResolution,
    FocalPlaneResolutionUnit,
    SubjectLocation,
    ExposureIndex,
    SensingMethod,
    FileSource,
    SceneType,
    CFAPattern,
    CustomRendered,
    ExposureMode,
    WhiteBalance,
    DigitalZoomRatio,
    FocalLengthIn35mmFilm,
    SceneCaptureType,
    GainControl,
    Contrast,
    Saturation,
    Sharpness,
    DeviceSettingDescription,
    SubjectDistanceRange,
    CompositeImage,
    SourceImageNumberOfCompositeImage,
    SourceExposureTimesOfCompositeImage,

    // Tags Relating to shooting situation
    Temperature,
    Humidity,
    Pressure,
    WaterDepth,
    Acceleration,
    CameraElevationAngle,

    // Other Tags
    ImageUniqueID,
    CameraOwnerName,
    BodySerialNumber,
    LensSpecification,
    LensMake,
    LensModel,
    LensSerialNumber,
}

pub fn get_usize_for_tag(tag: Tags) -> usize {
    match tag {
        Tags::ExifOffset => 34665,
        Tags::GPSOffset => 34853,
        Tags::Interoperability => 40965,
        Tags::ImageWidth => 256,
        Tags::ImageLength => 257,
        Tags::BitsPerSample => 258,
        Tags::Compression => 259,
        Tags::PhotometricInterpretation => 262,
        Tags::Orientation => 274,
        Tags::SamplesPerPixel => 277,
        Tags::PlanarConfiguration => 284,
        Tags::YCbCrSubSampling => 530,
        Tags::YCbCrPositioning => 531,
        Tags::XResolution => 282,
        Tags::YResolution => 283,
        Tags::ResolutionUnit => 296,
        Tags::StripOffsets => 273,
        Tags::RowsPerStrip => 278,
        Tags::StripByteCounts => 279,
        Tags::JPEGInterchangeFormat => 513,
        Tags::JPEGInterchangeFormatLength => 514,
        Tags::TransferFunction => 301,
        Tags::WhitePoint => 318,
        Tags::PrimaryChromaticities => 319,
        Tags::YCbCrCoefficients => 529,
        Tags::ReferenceBlackWhite => 532,
        Tags::DateTime => 306,
        Tags::ImageDescription => 270,
        Tags::Make => 271,
        Tags::Model => 272,
        Tags::Software => 305,
        Tags::Artist => 315,
        Tags::Copyright => 33432,
        // Exif
        Tags::ExifVersion => 36864,
        Tags::FlashpixVersion => 40960,
        Tags::ColorSpace => 40961,
        Tags::Gamma => 42240,
        Tags::ComponentsConfiguration => 37121,
        Tags::CompressedBitsPerPixel => 37122,
        Tags::PixelXDimension => 40962,
        Tags::PixelYDimension => 40963,
        Tags::MakerNote => 37500,
        Tags::UserComment => 37510,
        Tags::RelatedSoundFile => 40964,
        Tags::DateTimeOriginal => 36867,
        Tags::DateTimeDigitized => 36868,
        Tags::OffsetTime => 36880,
        Tags::OffsetTimeOriginal => 36881,
        Tags::OffsetTimeDigitized => 36882,
        Tags::SubSecTime => 37520,
        Tags::SubSecTimeOriginal => 37521,
        Tags::SubSecTimeDigitized => 37522,
        Tags::ExposureTime => 33434,
        Tags::FNumber => 33437,
        Tags::ExposureProgram => 34850,
        Tags::SpectralSensitivity => 34852,
        Tags::PhotographicSensitivity => 34855,
        Tags::OECF => 34856,
        Tags::SensitivityType => 34864,
        Tags::StandardOutputSensitivity => 34865,
        Tags::RecommendedExposureIndex => 34866,
        Tags::ISOSpeed => 34867,
        Tags::ISOSpeedLatitudeyyy => 34868,
        Tags::ISOSpeedLatitudezzz => 34869,
        Tags::ShutterSpeedValue => 37377,
        Tags::ApertureValue => 37378,
        Tags::BrightnessValue => 37379,
        Tags::ExposureBiasValue => 37380,
        Tags::MaxApertureValue => 37381,
        Tags::SubjectDistance => 37382,
        Tags::MeteringMode => 37383,
        Tags::LightSource => 37384,
        Tags::Flash => 37385,
        Tags::FocalLength => 37386,
        Tags::SubjectArea => 37396,
        Tags::FlashEnergy => 41483,
        Tags::SpatialFrequencyResponse => 41484,
        Tags::FocalPlaneXResolution => 41486,
        Tags::FocalPlaneYResolution => 41487,
        Tags::FocalPlaneResolutionUnit => 41488,
        Tags::SubjectLocation => 41492,
        Tags::ExposureIndex => 41493,
        Tags::SensingMethod => 41495,
        Tags::FileSource => 41728,
        Tags::SceneType => 41729,
        Tags::CFAPattern => 41730,
        Tags::CustomRendered => 41985,
        Tags::ExposureMode => 41986,
        Tags::WhiteBalance => 41987,
        Tags::DigitalZoomRatio => 41988,
        Tags::FocalLengthIn35mmFilm => 41989,
        Tags::SceneCaptureType => 41990,
        Tags::GainControl => 41991,
        Tags::Contrast => 41992,
        Tags::Saturation => 41993,
        Tags::Sharpness => 41994,
        Tags::DeviceSettingDescription => 41995,
        Tags::SubjectDistanceRange => 41996,
        Tags::CompositeImage => 42080,
        Tags::SourceImageNumberOfCompositeImage => 42081,
        Tags::SourceExposureTimesOfCompositeImage => 42082,
        Tags::Temperature => 37888,
        Tags::Humidity => 37889,
        Tags::Pressure => 37890,
        Tags::WaterDepth => 37891,
        Tags::Acceleration => 37892,
        Tags::CameraElevationAngle => 37893,
        Tags::ImageUniqueID => 42016,
        Tags::CameraOwnerName => 42032,
        Tags::BodySerialNumber => 42033,
        Tags::LensSpecification => 42034,
        Tags::LensMake => 42035,
        Tags::LensModel => 42036,
        Tags::LensSerialNumber => 42037,
    }
}

pub fn get_tag_for_usize(tag: usize) -> Option<Tags> {
    match tag {
        34665 => Some(Tags::ExifOffset),
        34853 => Some(Tags::GPSOffset),
        40965 => Some(Tags::Interoperability),
        256 => Some(Tags::ImageWidth),
        257 => Some(Tags::ImageLength),
        258 => Some(Tags::BitsPerSample),
        259 => Some(Tags::Compression),
        262 => Some(Tags::PhotometricInterpretation),
        274 => Some(Tags::Orientation),
        277 => Some(Tags::SamplesPerPixel),
        284 => Some(Tags::PlanarConfiguration),
        530 => Some(Tags::YCbCrSubSampling),
        531 => Some(Tags::YCbCrPositioning),
        282 => Some(Tags::XResolution),
        283 => Some(Tags::YResolution),
        296 => Some(Tags::ResolutionUnit),
        273 => Some(Tags::StripOffsets),
        278 => Some(Tags::RowsPerStrip),
        279 => Some(Tags::StripByteCounts),
        513 => Some(Tags::JPEGInterchangeFormat),
        514 => Some(Tags::JPEGInterchangeFormatLength),
        301 => Some(Tags::TransferFunction),
        318 => Some(Tags::WhitePoint),
        319 => Some(Tags::PrimaryChromaticities),
        529 => Some(Tags::YCbCrCoefficients),
        532 => Some(Tags::ReferenceBlackWhite),
        306 => Some(Tags::DateTime),
        270 => Some(Tags::ImageDescription),
        271 => Some(Tags::Make),
        272 => Some(Tags::Model),
        305 => Some(Tags::Software),
        315 => Some(Tags::Artist),
        33432 => Some(Tags::Copyright),
        // Exif
        36864 => Some(Tags::ExifVersion),
        40960 => Some(Tags::FlashpixVersion),
        40961 => Some(Tags::ColorSpace),
        42240 => Some(Tags::Gamma),
        37121 => Some(Tags::ComponentsConfiguration),
        37122 => Some(Tags::CompressedBitsPerPixel),
        40962 => Some(Tags::PixelXDimension),
        40963 => Some(Tags::PixelYDimension),
        37500 => Some(Tags::MakerNote),
        37510 => Some(Tags::UserComment),
        40964 => Some(Tags::RelatedSoundFile),
        36867 => Some(Tags::DateTimeOriginal),
        36868 => Some(Tags::DateTimeDigitized),
        36880 => Some(Tags::OffsetTime),
        36881 => Some(Tags::OffsetTimeOriginal),
        36882 => Some(Tags::OffsetTimeDigitized),
        37520 => Some(Tags::SubSecTime),
        37521 => Some(Tags::SubSecTimeOriginal),
        37522 => Some(Tags::SubSecTimeDigitized),
        33434 => Some(Tags::ExposureTime),
        33437 => Some(Tags::FNumber),
        34850 => Some(Tags::ExposureProgram),
        34852 => Some(Tags::SpectralSensitivity),
        34855 => Some(Tags::PhotographicSensitivity),
        34856 => Some(Tags::OECF),
        34864 => Some(Tags::SensitivityType),
        34865 => Some(Tags::StandardOutputSensitivity),
        34866 => Some(Tags::RecommendedExposureIndex),
        34867 => Some(Tags::ISOSpeed),
        34868 => Some(Tags::ISOSpeedLatitudeyyy),
        34869 => Some(Tags::ISOSpeedLatitudezzz),
        37377 => Some(Tags::ShutterSpeedValue),
        37378 => Some(Tags::ApertureValue),
        37379 => Some(Tags::BrightnessValue),
        37380 => Some(Tags::ExposureBiasValue),
        37381 => Some(Tags::MaxApertureValue),
        37382 => Some(Tags::SubjectDistance),
        37383 => Some(Tags::MeteringMode),
        37384 => Some(Tags::LightSource),
        37385 => Some(Tags::Flash),
        37386 => Some(Tags::FocalLength),
        37396 => Some(Tags::SubjectArea),
        41483 => Some(Tags::FlashEnergy),
        41484 => Some(Tags::SpatialFrequencyResponse),
        41486 => Some(Tags::FocalPlaneXResolution),
        41487 => Some(Tags::FocalPlaneYResolution),
        41488 => Some(Tags::FocalPlaneResolutionUnit),
        41492 => Some(Tags::SubjectLocation),
        41493 => Some(Tags::ExposureIndex),
        41495 => Some(Tags::SensingMethod),
        41728 => Some(Tags::FileSource),
        41729 => Some(Tags::SceneType),
        41730 => Some(Tags::CFAPattern),
        41985 => Some(Tags::CustomRendered),
        41986 => Some(Tags::ExposureMode),
        41987 => Some(Tags::WhiteBalance),
        41988 => Some(Tags::DigitalZoomRatio),
        41989 => Some(Tags::FocalLengthIn35mmFilm),
        41990 => Some(Tags::SceneCaptureType),
        41991 => Some(Tags::GainControl),
        41992 => Some(Tags::Contrast),
        41993 => Some(Tags::Saturation),
        41994 => Some(Tags::Sharpness),
        41995 => Some(Tags::DeviceSettingDescription),
        41996 => Some(Tags::SubjectDistanceRange),
        42080 => Some(Tags::CompositeImage),
        42081 => Some(Tags::SourceImageNumberOfCompositeImage),
        42082 => Some(Tags::SourceExposureTimesOfCompositeImage),
        37888 => Some(Tags::Temperature),
        37889 => Some(Tags::Humidity),
        37890 => Some(Tags::Pressure),
        37891 => Some(Tags::WaterDepth),
        37892 => Some(Tags::Acceleration),
        37893 => Some(Tags::CameraElevationAngle),
        42016 => Some(Tags::ImageUniqueID),
        42032 => Some(Tags::CameraOwnerName),
        42033 => Some(Tags::BodySerialNumber),
        42034 => Some(Tags::LensSpecification),
        42035 => Some(Tags::LensMake),
        42036 => Some(Tags::LensModel),
        42037 => Some(Tags::LensSerialNumber),
        _ => None,
    }
}
